from django.contrib import admin

from .models import *

admin.site.register(Sex)
admin.site.register(MaritalStatus)
admin.site.register(Difficulty)
admin.site.register(Tag)
admin.site.register(Rarity)
admin.site.register(Stock)
admin.site.register(Skill)
admin.site.register(GameType)
admin.site.register(LevelStatus)
admin.site.register(User)
admin.site.register(Theme)
admin.site.register(Theory)
admin.site.register(TheoryDatum)
admin.site.register(TheoryDatumTag)
admin.site.register(MiniGame)
admin.site.register(Level)
admin.site.register(Route)
admin.site.register(LevelTag)
admin.site.register(UserLevel)
admin.site.register(UserMiniGameReward)
admin.site.register(UserTheoryReward)
